name: resep_minuman_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
